// Generated by CoffeeScript 1.8.0
(function() {
  $.fn.shyHeader = function(options) {
    var currentOffset, defaults, downHandler, isHidden, lastScrollPos, startingPos, upHandler;
    this.addClass("shyHeader");
    defaults = {
      distanceBeforeHide: 250,
      distanceBeforeShow: 0,
      elemToHide: this,
      visiblePos: 0,
      hiddenPos: -this.outerHeight(),
      duration: 0.3,
      visibleClass: "visible",
      hiddenClass: "hidden",
      useJS: true,
      destroy: false
    };
    options = $.extend(defaults, options);
    startingPos = options['elemToHide'].offset().top;
    currentOffset = $(window).scrollTop();
    lastScrollPos = 0;
    isHidden = false;
    if (!options['destroy']) {
      $(window).on("scroll", function(e) {
        var _scrollTop;
        _scrollTop = $(window).scrollTop();
        if (_scrollTop > lastScrollPos) {
          downHandler(_scrollTop, options['elemToHide']);
        } else {
          upHandler(_scrollTop, options['elemToHide']);
        }
        return lastScrollPos = _scrollTop;
      });
      downHandler = function(_st, el) {
        if ((_st >= currentOffset + options['distanceBeforeHide']) && !isHidden) {
          if (options['useJS']) {
            TweenLite.to(options['elemToHide'], options['duration'], {
              top: options['hiddenPos'],
              ease: Quint.easeOut
            });
          }
          el.removeClass("shy-visible");
          el.addClass("shy-hidden");
          return isHidden = true;
        } else {

        }
      };
      return upHandler = function(_st, el) {
        if (isHidden) {
          if (options['useJS']) {
            TweenLite.to(options['elemToHide'], options['duration'], {
              top: options['visiblePos'],
              ease: Quint.easeOut
            });
          }
          isHidden = false;
          el.removeClass("shy-hidden");
          el.addClass("shy-visible");
        }
        return currentOffset = _st;
      };
    } else {
      this.removeClass("shyHeader");
      this.removeClass("shy-visible");
      this.removeClass("shy-hidden");
      return options['elemToHide'].css({
        "top": ""
      });
    }
  };

}).call(this);
