// Generated by CoffeeScript 1.8.0
(function() {
  $.fn.shyHeader = function(options) {
    var currentOffset, defaults, downHandler, isHidden, lastScrollPos, startingPos, upHandler;
    this.addClass("shyHeader");
    defaults = {
      distanceBeforeHide: 250,
      distanceBeforeShow: 0,
      elemToHide: this,
      visiblePos: 32,
      hiddenPos: -5,
      duration: 0.3,
      visibleClass: "visible",
      hiddenClass: "hidden",
      useJS: true
    };
    options = $.extend(defaults, options);
    startingPos = options['elemToHide'].offset().top;
    currentOffset = 0;
    lastScrollPos = 0;
    isHidden = false;
    $(window).on("scroll", function(e) {
      var _scrollTop;
      _scrollTop = $(window).scrollTop();
      if (_scrollTop > lastScrollPos) {
        downHandler(_scrollTop);
      } else {
        upHandler(_scrollTop);
      }
      return lastScrollPos = _scrollTop;
    });
    downHandler = function(_st) {
      if ((_st >= currentOffset + options['distanceBeforeHide']) && !isHidden) {
        if (useJS) {
          TweenLite.to(options['elemToHide'], options['duration'], {
            top: options['hiddenPos'],
            easing: Quint.easeOut
          });
        }
        this.addClass("hidden");
        return isHidden = true;
      } else {

      }
    };
    return upHandler = function(_st) {
      if (isHidden) {
        if (useJS) {
          TweenLite.to(options['elemToHide'], options['duration'], {
            top: options['visiblePos'],
            easing: Quint.easeOut
          });
        }
        isHidden = false;
        this.addClass("visible");
      }
      return currentOffset = _st;
    };
  };

}).call(this);
